---
- name: Add repository for Debian Buster 32bit
  apt_repository:
    repo: "{{ item }}"
    state: present
  become: yes
  with_items:
    - deb http://mirrordirector.raspbian.org/raspbian/ stable main contrib non-free rpi firmware
    - deb http://archive.raspberrypi.org/debian/ stretch main ui
  when: 
    - ansible_distribution == "Debian"
    - ansible_distribution_release == "buster"
    - ansible_facts.userspace_bits == "32"

- name: Register Keys for Debian Buster
  apt_key:
    url: "{{ item }}"
    state: present
  become: yes
  with_items:
    - https://ftp-master.debian.org/keys/archive-key-10-security.asc
    - https://ftp-master.debian.org/keys/archive-key-10.asc
  when: 
    - ansible_distribution == "Debian"
    - ansible_distribution_release == "buster"